"""added is_completed cloumn to stages table to check wether the stage is completed or not

Revision ID: 09e12a19c5c4
Revises: fedad94445e8
Create Date: 2025-04-23 12:26:41.502266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '09e12a19c5c4'
down_revision: Union[str, None] = 'fedad94445e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE stages SET is_completed = FALSE WHERE is_completed IS NULL")

    op.alter_column('stages', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
