"""trail

Revision ID: 962a17b6007e
Revises: 4452b1eceb9c
Create Date: 2025-04-07 17:13:12.398630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '962a17b6007e'
down_revision: Union[str, None] = '4452b1eceb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_assessment_response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_assessment_response',
    sa.Column('response_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cycle_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['employee_allocation.allocation_id'], name='self_assessment_response_allocation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycle.cycle_id'], name='self_assessment_response_cycle_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], name='self_assessment_response_employee_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.option_id'], name='self_assessment_response_option_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='self_assessment_response_question_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id', name='self_assessment_response_pkey')
    )
    # ### end Alembic commands ###
