"""added is_active cloumn to stages table

Revision ID: bbbab73cf267
Revises: 6387dd1dfa17
Create Date: 2025-04-22 15:19:55.008805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'bbbab73cf267'
down_revision: Union[str, None] = '6387dd1dfa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'is_active')
    # ### end Alembic commands ###
