"""added self assessment response table

Revision ID: c465fdb1bfe9
Revises: 962a17b6007e
Create Date: 2025-04-07 17:33:03.073856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c465fdb1bfe9'
down_revision: Union[str, None] = '962a17b6007e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_assessment_response',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['employee_allocation.allocation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cycle_id'], ['appraisal_cycle.cycle_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.option_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_assessment_response')
    # ### end Alembic commands ###
