"""Added unique contraint for employee_assignemnt

Revision ID: ec17e421cd64
Revises: c465fdb1bfe9
Create Date: 2025-04-08 23:21:10.875931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ec17e421cd64'
down_revision: Union[str, None] = 'c465fdb1bfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_employee_question_cycle', 'assigned_questions', ['employee_id', 'question_id', 'cycle_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_employee_question_cycle', 'assigned_questions', type_='unique')
    # ### end Alembic commands ###
