"""added is_completed cloumn to stages table to check wether the stage is completed or not

Revision ID: fedad94445e8
Revises: eda20296a46c
Create Date: 2025-04-23 12:19:11.308118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'fedad94445e8'
down_revision: Union[str, None] = 'eda20296a46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.alter_column('stages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('stages', 'is_completed')
    # ### end Alembic commands ###
